name: Test GHCR GIT_TOKEN

on:
  pull_request:

jobs:
  test-ghcr-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GHCR using PACKAGES_READ_TOKEN
        run: |
          echo "${{ secrets.PACKAGES_READ_TOKEN }}" | docker login ghcr.io -u xataio --password-stdin

      - name: Test pull image
        run: |
          docker pull ghcr.io/xataio/postgres-images/cnpg-postgres-plus:9c38125077fe27cd45c55234806eb42603460a39
